- project:
    templates:
      - puppet-beaker-jobs
    check:
      jobs:
        - legacy-puppet-midonet-puppet-unit-3.6-centos-7:
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
        - legacy-puppet-midonet-puppet-unit-3.8-centos-7:
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
        - legacy-puppet-midonet-puppet-unit-4.5-centos-7:
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
        - legacy-puppet-midonet-puppet-unit-latest-centos-7:
            voting: false
            branches: ^master
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
    gate:
      jobs:
        - legacy-puppet-midonet-puppet-unit-3.6-centos-7:
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
        - legacy-puppet-midonet-puppet-unit-3.8-centos-7:
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
        - legacy-puppet-midonet-puppet-unit-4.5-centos-7:
            irrelevant-files:
              - ^.*\.md$
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^metadata.json$
              - ^releasenotes/.*$
              - ^test-requirements.txt$
